name: geo_fencing_android
description: "Android implementation of geo_fencing plugin."
version: 1.0.0
homepage: https://github.com/yourusername/flutter_geo_fencing

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # Note: This is a path dependency for development.
  # For publishing, this should be replaced with: geo_fencing_platform_interface: ^1.0.0
  geo_fencing_platform_interface:
    path: ../geo_fencing_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  plugin:
    platforms:
      android:
        package: com.geofencing.android
        pluginClass: GeoFencingAndroidPlugin
